
services:
  frontend-pull:
    env_file: .env
    image: timeartist/redisfi
    command:  poetry run redisfi web server
    ports:
      - 8000:8000
    profiles:
      - pull
  bridge-pull:
    env_file: .env
    image: timeartist/redisfi
    command: poetry run redisfi bridge up
    profiles:
      - pull
  frontend-build:
    env_file: .env
    build: .
    command: poetry run redisfi web server
    ports:
      - 8000:8000
    profiles:
      - build
  bridge-build:
    env_file: .env
    build: .
    command: poetry run redisfi bridge up
    profiles:
      - build
  redis:
    image: redislabs/redisearch:2.4.0
    ports: 
     - 6379:6379
    profiles:
      - pull_redis
