
services:
  frontend-pull:
    env_file: .env
    image: gcr.io/redislabs-university/redisfi:99.99.99
    command:  poetry run redisfi web server
    ports:
      - 8000:8000
    profiles:
      - pull
  historic-pull:
    env_file: .env
    image: gcr.io/redislabs-university/redisfi:99.99.99
    command: poetry run redisfi bridge historic 
    profiles:
      - pull
  metadata-pull:
    env_file: .env
    image: gcr.io/redislabs-university/redisfi:99.99.99
    command: poetry run redisfi bridge metadata 
    profiles:
      - pull
  live-pull:
    env_file: .env
    image: gcr.io/redislabs-university/redisfi:99.99.99
    command: poetry run redisfi bridge live
    profiles:
      - pull
  frontend-build:
    env_file: .env
    build: .
    command: poetry run redisfi web server
    ports:
      - 8000:8000
    profiles:
      - build
  historic-build:
    env_file: .env
    build: .
    command: poetry run redisfi bridge historic
    profiles:
      - build
  metadata-build:
    env_file: .env
    build: .
    command: poetry run redisfi bridge metadata
    profiles:
      - build
  live-build:
    env_file: .env
    build: .
    command: poetry run redisfi bridge live
    profiles:
      - build
  redis:
    image: redislabs/redisearch:2.4.0
    ports: 
     - 6379:6379
    profiles:
      - pull_redis
