
services:
  frontend-pull:
    env_file: .env
    image: technicalenablement/redisfi
    command:  poetry run redisfi web server
    pull_policy: always
    container_name: frontend
    ports:
      - 8000:8000
    profiles:
      - pull
  bridge-pull:
    env_file: .env
    image: technicalenablement/redisfi
    command: poetry run redisfi bridge up ${ALPACA_KEY} ${ALPACA_SECRET}
    container_name: bridge
    pull_policy: always
    profiles:
      - pull
      - deployed-prebuilt
  vss-wsapi-pull:
    env_file: .env
    image: technicalenablement/redisfi-vss
    command: poetry run VSS run
    container_name: vss-wsapi
    pull_policy: always
    ports:
     - 7777:7777
    profiles:
      - vss-pull
  vss-loader-pull:
    env_file: .env
    image: technicalenablement/redisfi-vss
    command: poetry run VSS load -n
    container_name: vss-loader
    pull_policy: always
    volumes:
      - /tmp/redisfi_work_dir:/tmp:rw
    profiles:
      - vss-pull
  frontend-build:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/local.dockerfile
    container_name: frontend
    ports:
      - 8000:8000
    profiles:
      - build
    command: poetry run redisfi web server
  bridge-build:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/local.dockerfile
    command: poetry run redisfi bridge up ${ALPACA_KEY} ${ALPACA_SECRET}
    container_name: bridge
    profiles:
      - build
  vss-build:
    env_file: .env
    build: ../redisfi-vss
    command: poetry run VSS run
    container_name: vss-wsapi
    ports:
     - 7777:7777
    profiles:
      - vss-build
  vss-loader-build:
    env_file: .env
    build: ../redisfi-vss
    command: poetry run VSS load -n
    container_name: vss-loader
    pull_policy: always
    volumes:
      - /tmp/redisfi_work_dir:/tmp:rw
    profiles:
      - vss-build
  frontend-deployed-prebuilt:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/deployed.dockerfile
      args:
        BASE: ${BASE}
        DOMAIN: ${DOMAIN}
        CERT_NAME: ${CERT_NAME}
    container_name: frontend
    ports:
      - 443:443
    profiles:
      - deployed-prebuilt
  redis:
    image: redislabs/redisearch:2.4.3
    ports: 
     - 6379:6379
    profiles:
      - pull_redis
  
