
services:
  frontend-pull:
    env_file: .env
    image: timeartist/redisfi
    command:  poetry run redisfi web server
    pull_policy: always
    ports:
      - 8000:8000
    profiles:
      - pull
  bridge-pull:
    env_file: .env
    image: timeartist/redisfi
    command: poetry run redisfi bridge up
    pull_policy: always
    profiles:
      - pull
  vss-pull:
    env_file: .env
    image: timeartist/redisfi-vss
    command: poetry run VSS run
    container_name: vss
    pull_policy: always
    ports:
     - 7777:7777
    profiles:
      - pull
  frontend-build:
    env_file: .env
    build: .
    command: poetry run redisfi web server
    ports:
      - 8000:8000
    profiles:
      - build
  bridge-build:
    env_file: .env
    build: .
    command: poetry run redisfi bridge up
    profiles:
      - build
  vss-build:
    env_file: .env
    build: ../redisfi-vss
    command: poetry run VSS run
    container_name: vss
    ports:
     - 7777:7777
    profiles:
      - build
  redis:
    image: redislabs/redisearch:2.4.2
    ports: 
     - 6379:6379
    profiles:
      - pull_redis
