[tool.poetry]
name = "redisfi"
version = "0.1.0"
description = ""
authors = ["Adi Wabisabi <adi.wabisabi@redis.com>"]

[tool.poetry.scripts]
redisfi = "redisfi.cli:run"

[tool.poetry.dependencies]
python = "3.9.10"
cleo = "^0.8.1"
redis = "^4.1.2"
alpaca-trade-api = "^1.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
