resources:
  - name: redisfi
    type: git
    icon: github
    source:
      uri: https://github.com/redislabs-training/redisfi
      branch: main
      username: ((auth-github))
      password: x-oauth-basic
  - name: docent
    type: git
    icon: github
    source:
      uri: https://github.com/redislabs-training/docent
      branch: main
      username: ((auth-github))
      password: x-oauth-basic
jobs:
  - name: create-cluster
    plan:
      - get: docent
      - task: deploy
        file: docent/gallery/cluster/create.yml
        params:
          WORKSPACE: redisfi-((guid))
          NAME_SLUG: ((hostname)).fi
          MACHINE_TYPE: e2-standard-8
    on_failure:
      task: teardown
      file: docent/gallery/cluster/destroy.yml
      params:
          NAME_SLUG: ((hostname)).fi
          WORKSPACE: redisfi-((guid))
  - name: deploy-app
    plan:
      - get: docent
        passed: [create-cluster]
        trigger: true
      - get: redisfi
      - task: deploy
        privileged: true
        file: redisfi/gallery/deploy.yml
        params:
          WORKSPACE: redisfi-((guid))
          NAME_SLUG: ((hostname)).fi
          ALPACA_KEY: ((alpaca-key))
          ALPACA_SECRET: ((alpaca-secret))
  - name: build-dbs
    plan:
      - get: redisfi
        passed: [deploy-app]
        trigger: true
      - get: docent
        passed: [deploy-app]
        trigger: true
      - task: deploy
        privileged: true
        file: redisfi/gallery/db-readycheck.yml
        params:
          NAME_SLUG: ((hostname)).fi
          GUID: ((guid))
          SECRET: ((secret))
  - name: teardown-app
    plan:
      - get: redisfi
        passed: [deploy-app]
      - get: docent
        passed: [deploy-app]
      - task: teardown
        privileged: true
        file: redisfi/gallery/teardown.yml
        params:
          WORKSPACE: redisfi-((guid))
          NAME_SLUG: ((hostname)).fi
  - name: destroy-cluster
    plan:
      - get: docent
        passed: [teardown-app]
        trigger: true
      - task: teardown
        file: docent/gallery/cluster/destroy.yml
        params:
          WORKSPACE: redisfi-((guid))
          NAME_SLUG: ((hostname)).fi