resources:
  - name: redisfi
    type: git
    icon: github
    source:
      uri: https://github.com/redislabs-training/redisfi
      branch: main
      username: ((auth-github))
      password: x-oauth-basic
  - name: redisfi-vss
    type: git
    icon: github
    source:
      uri: https://github.com/redislabs-training/redisfi-vss
      branch: main
      username: ((auth-github))
      password: x-oauth-basic
  # - name: redis-enterprise
  #   icon: docker
  #   type: registry-image
  #   source:
  #     repository: redislabs/redis
  #     tag: latest
  - name: redisfi-container
    type: registry-image
    icon: docker
    source:
      repository: timeartist/redisfi
      username: timeartist
      password: ((auth-docker))
  - name: redisfi-vss-container
    type: registry-image
    icon: docker
    source:
      repository: timeartist/redisfi-vss
      username: timeartist
      password: ((auth-docker))

jobs: 
  - name: build-container
    plan:
      - get: redisfi
        trigger: true
        params:
          format: oci
      - task: build
        privileged: true
        file: redisfi/ci/build.yml
      - put: redisfi-container
        params:
          image: image/image.tar
          version: 99.99.99
          bump_aliases: true
  - name: build-vss-container
    plan:
      - get: redisfi-vss
        trigger: true
        params:
          format: oci
      - task: build
        privileged: true
        file: redisfi-vss/ci/build-vss.yml
      - put: redisfi-vss-container
        params:
          image: image/image.tar
          version: 99.99.99
          bump_aliases: true